[[library]]
type="git"
name="sdlpp"
path="https://github.com/antonte/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="git"
name="sdl2"
path="https://github.com/antonte/sdl2-devel.git"
incdir="include"
libdir="lib/x64"
includes=["SDL.h"]

[[library]]
type="lib"
name="GL"
includes=["SDL_opengl.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/skystrife/cpptoml.git"
includes=["cpptoml.h"]
incdir="include"

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

# file repos WIP

[[library]]
type="file"
name="shade"
path="/home/anton/prj/shade"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/texture_library.hpp",
  "shade/var.hpp"
]

[[library]]
type="file"
name="log"
includes=["log/log.hpp"]
path="/home/anton/prj/log"

[[library]]
type="file"
name="coeff"
includes=["coeff/coeff.hpp", "coeff/coeff_reg.hpp"]
path="/home/anton/prj/coeff"
