[[library]]
type="git"
name="sdlpp"
path="git@github.com:antonte/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="pkgconfig"
name="sdl2"
includes=["SDL.h"]

[[library]]
type="pkgconfig"
name="SDL2_ttf"
includes=["SDL_ttf.h"]

[[library]]
type="pkgconfig"
name="SDL2_image"
includes=["SDL_image.h"]

[[library]]
type="pkgconfig"
name="fftw3"
includes=["fftw3.h"]

[[library]]
type="pkgconfig"
name="libswscale"
includes=["libswscale/swscale.h"]

[[library]]
type="pkgconfig"
name="libavformat"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavdevice"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="pkgconfig"
name="libpulse"
includes=["pulse/thread-mainloop.h", "pulse/context.h", "pulse/stream.h", "pulse/scache.h"]

[[library]]
type="pkgconfig"
name="gsl"
includes=["gsl/gsl_fit.h"]

[[library]]
type="pkgconfig"
name="jsoncpp"
includes=["json/json.h"]

[[library]]
type="lib"
name="glut"
includes=["GL/glut.h"]

[[library]]
type="lib"
name="GL"
includes=["SDL_opengl.h", "GL/glut.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/skystrife/cpptoml.git"
postClone="mv include/* ."
includes=["cpptoml/cpptoml.h"]

# file repos WIP

[[library]]
type="file"
name="shade"
path="/home/anton/prj/shade"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/texture_library.hpp",
  "shade/var.hpp"
]

[[library]]
type="file"
name="log"
includes=["log/log.hpp"]
path="/home/anton/prj/log"

[[library]]
type="file"
name="coeff"
includes=["coeff/coefficient.hpp", "coeff/coefficient_registry.hpp"]
path="/home/anton/prj/coeff"
