[[library]]
type="git"
name="sdlpp"
path="https://github.com/antonte/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="pkgconfig"
name="sdl2"
includes=["SDL.h"]

[[library]]
type="pkgconfig"
name="SDL2_ttf"
includes=["SDL_ttf.h"]

[[library]]
type="pkgconfig"
name="SDL2_image"
includes=["SDL_image.h"]

[[library]]
type="pkgconfig"
name="fftw3"
includes=["fftw3.h"]

[[library]]
type="pkgconfig"
name="libswscale"
includes=["libswscale/swscale.h"]

[[library]]
type="pkgconfig"
name="libavformat"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavdevice"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="pkgconfig"
name="libpulse"
includes=["pulse/thread-mainloop.h", "pulse/context.h", "pulse/stream.h", "pulse/scache.h"]

[[library]]
type="pkgconfig"
name="gsl"
includes=["gsl/gsl_fit.h"]

[[library]]
type="pkgconfig"
name="jsoncpp"
includes=["json/json.h"]

[[library]]
type="lib"
name="glut"
includes=["GL/glut.h"]

[[library]]
type="pkgconfig"
name="libuv"
includes=["uv.h"]

[[library]]
type="framework"
name="OpenGL"
includes=["SDL_opengl.h", "GL/glut.h", "OpenGL/gl3.h", "GL/glew.h"]

[[library]]
type="lib"
name="GLEW"
includes=["GL/glew.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/skystrife/cpptoml.git"
includes=["cpptoml.h"]
incdir="include"

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="lib"
name="tomcrypt"
includes=["tomcrypt.h"]

[[library]]
type="lib"
name="tommath"
includes=["tomcrypt.h"]

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="catch2"
path="https://github.com/catchorg/Catch2.git"
includes=["catch.hpp"]
incdir="single_include/catch2"

# file repos WIP

[[library]]
type="git"
name="shade"
path="https://github.com/antonte/shade.git"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/texture_library.hpp",
  "shade/var.hpp"
]

[[library]]
type="git"
name="log"
includes=["log/log.hpp"]
path="https://github.com/antonte/log.git"

[[library]]
type="git"
name="coeff"
includes=["coeff/coeff.hpp", "coeff/coeff_reg.hpp"]
path="https://github.com/antonte/coeff.git"

[[library]]
type="file"
name="net"
path="/home/anton/prj/irl/net"
includes=[
  "net/conn.hpp",
  "net/server.hpp"
]

[[library]]
type="file"
name="sched"
path="/home/anton/prj/irl/sched"
includes=[
  "sched/sched.hpp"
]
