[[library]]
type="git"
name="sdlpp"
path="https://github.com/antonte/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="lib"
name="Ws2_32"
includes=["Winsock2.h"]

[[library]]
type="git"
name="sdl2"
path="https://github.com/antonte/sdl2-devel.git"
incdir="include"
libdir="lib/x64"
includes=["SDL.h"]

[[library]]
type="lib"
name="glut"
includes=["GL/glut.h"]

[[library]]
type="lib"
name="libuv"
includes=["uv.h"]

[[library]]
type="lib"
name="GL"
includes=["SDL_opengl.h", "GL/glut.h"]

[[library]]
type="lib"
name="SDL2main"
includes=["SDL.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/skystrife/cpptoml.git"
includes=["cpptoml.h"]
incdir="include"

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="catch2"
path="https://github.com/catchorg/Catch2.git"
includes=["catch2/catch.hpp"]
incdir="single_include"

[[library]]
type="git"
name="easy_draw"
path="https://github.com/antonte/easy-draw.git"
includes=[
  "easy_draw/easy_draw.hpp"
]

# file repos WIP

[[library]]
type="git"
name="shade"
path="https://github.com/antonte/shade.git"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/texture_library.hpp",
  "shade/var.hpp"
]

[[library]]
type="git"
name="log"
includes=["log/log.hpp"]
path="https://github.com/antonte/log.git"

[[library]]
type="git"
name="coeff"
includes=["coeff/coeff.hpp", "coeff/coeff_reg.hpp"]
path="https://github.com/antonte/coeff.git"

[[library]]
type="git"
name="glm"
includes=[ "glm/gtx/normal.hpp", "glm/gtx/transform.hpp", "glm/gtx/vec_swizzle.hpp", "glm/mat4x4.hpp", "glm/vec2.hpp", "glm/vec3.hpp" ]
path="https://github.com/g-truc/glm.git"
incdir="."

[[library]]
type="file"
name="net"
path="/home/anton/prj/irl/net"
includes=[
  "net/client.hpp",
  "net/server.hpp"
]

[[library]]
type="file"
name="sched"
path="/home/anton/prj/irl/sched"
includes=[
  "sched/sched.hpp"
]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="lib"
name="tomcrypt"
includes=["tomcrypt.h"]
